import { LegalLayout } from './LegalLayout';
import { usePageTitle } from '../../hooks/usePageTitle';

export default function TermsOfUse() {
  usePageTitle('Terms of Use · ResiHub');
  return (
    <LegalLayout title="Terms of Use" lastUpdated="01 May 2026">
      <p>
        These Terms govern your use of ResiHub ("the platform"), operated
        by Athera. By creating an account or signing in you agree to
        these Terms. If you do not agree, do not use the platform.
      </p>

      <h2>1. Eligibility</h2>
      <p>
        You must be at least 18 years old and a current or prospective
        resident of a property managed via ResiHub, or an authorised
        administrator of such a property. You confirm the information
        you provide at sign-up is accurate and that you'll keep it
        current.
      </p>

      <h2>2. Account responsibility</h2>
      <ul>
        <li>You're responsible for safeguarding your password. Use a strong, unique one.</li>
        <li>You may not share your account or transfer it to anyone else.</li>
        <li>Tell us immediately at <a href="mailto:security@resihub.co">security@resihub.co</a> if you suspect unauthorised access.</li>
        <li>We may suspend or deactivate accounts that breach these Terms or that pose a security risk.</li>
      </ul>

      <h2>3. What ResiHub is — and isn't</h2>
      <p>
        ResiHub is a tool for managing residence operations: room
        allocation, rent invoicing, visitor passes, maintenance tickets,
        chore-board, and resident communication. It is{' '}
        <strong>not</strong> a payment processor, a financial service,
        an estate agent, or a legal-advice service.
      </p>
      <ul>
        <li>Rent payments occur outside ResiHub (EFT, instant transfer, etc.). The platform records your proof and your administrator clears the invoice manually.</li>
        <li>Lease contracts you sign in-app are evidenced electronically; the underlying lease relationship is between you and your residence — not Athera.</li>
        <li>The platform does not give legal, financial, or property-law advice. Speak to a qualified professional for those.</li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You agree <strong>not</strong> to:</p>
      <ul>
        <li>Upload content that is illegal, harassing, hateful, or infringes someone else's rights.</li>
        <li>Submit fraudulent payment proofs, fake maintenance tickets, or impersonate another resident.</li>
        <li>Try to access another resident's account, data, or files.</li>
        <li>Probe, scan, or stress-test the platform for security weaknesses without our written permission.</li>
        <li>Use the platform to send spam or unsolicited communication to other residents.</li>
        <li>Reverse-engineer, decompile, or copy the platform's source code or design.</li>
      </ul>
      <p>
        Breach of this section can result in immediate account
        deactivation, legal action, and disclosure to your residence
        administrator and law enforcement if appropriate.
      </p>

      <h2>5. Content you upload</h2>
      <p>
        You retain ownership of files you upload (avatars, payment
        proofs, maintenance photos, chore proofs, contractor receipts).
        You grant us a limited licence to store, display, and process
        them solely to operate the service for you and your residence.
        We do not use uploaded content for training models, marketing,
        or any unrelated purpose.
      </p>
      <p>
        Don't upload content that violates someone else's privacy or
        that you don't have the right to share.
      </p>

      <h2>6. Payments to contractors and rent invoices</h2>
      <ul>
        <li>Rent invoices are generated by your residence administrator (or by you for a chosen month). Amounts are derived from your active allocation rent.</li>
        <li>Contractor invoices are managed by the administrator. Payments to contractors happen outside the platform.</li>
        <li>Marking an invoice "Paid" is a record-keeping action by an administrator. It does not constitute a financial guarantee from Athera.</li>
      </ul>

      <h2>7. Communication & notifications</h2>
      <p>
        We send you transactional notifications (new invoices, chore
        approvals, residence announcements) via in-app pop-ups and, if
        configured, email. You can mute non-essential notifications in
        your profile but cannot opt out of essential notices (e.g.
        unpaid rent, account-deactivation).
      </p>

      <h2>8. Service availability</h2>
      <p>
        We aim for high uptime but do not guarantee uninterrupted
        service. Maintenance windows, third-party outages, and
        unforeseen issues may cause occasional downtime. We will not be
        liable for indirect or consequential damages arising from
        downtime.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        The platform is provided <strong>"as is"</strong>. To the
        fullest extent permitted by South African law, we disclaim all
        implied warranties — fitness for a particular purpose,
        merchantability, and non-infringement. We are not liable for any
        loss of profit, loss of data, or indirect damages arising from
        your use of the platform, except where caused by our gross
        negligence or wilful misconduct.
      </p>

      <h2>10. Termination</h2>
      <ul>
        <li>You may close your account at any time by contacting your residence administrator or emailing <a href="mailto:privacy@resihub.co">privacy@resihub.co</a>.</li>
        <li>We may suspend or terminate your account if you breach these Terms, if your residence ends your tenancy, or if continued operation would put others at risk.</li>
        <li>On termination, we retain records as described in the Privacy Policy.</li>
      </ul>

      <h2>11. Changes to these Terms</h2>
      <p>
        We may update these Terms as the platform evolves. Material
        changes will be communicated via in-app notification at least 14
        days before they take effect. Continued use after the effective
        date means you accept the updated Terms.
      </p>

      <h2>12. Governing law and disputes</h2>
      <p>
        These Terms are governed by the laws of the Republic of South
        Africa. Any dispute will first be addressed in good faith
        between us and you; if unresolved, it will be referred to the
        appropriate court in the jurisdiction where your residence is
        located.
      </p>

      <h2>13. Contact</h2>
      <p>
        Questions about these Terms — email{' '}
        <a href="mailto:legal@resihub.co">legal@resihub.co</a>.
      </p>
    </LegalLayout>
  );
}
