import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatPeriod, formatRand } from './period';

/**
 * PDF generation for student-facing documents. Real PDFs (vector text,
 * proper page sizing) — replaces the HTML blob downloads.
 */

interface InvoiceData {
  id:           string;
  period:       string | null;
  amount:       string | null;
  status:       string | null;
  proofStatus?: string | null;
  createdAt:    string;
  user:         { name: string; email: string; phone?: string | null };
  room?:        { number: string; block: string; type: string };
  rentLineItem: number;       // resolved rent figure (string→number)
}

interface ContractData {
  id:           string;
  period:       string | null;
  status:       string | null;
  signedAt?:    string | null;
  signedByName?: string | null;
  user:         { name: string; email: string };
  room?:        { number: string; block: string; type: string; price: number };
  startDate:    string;
}

const CYAN = '#00CCCC';
const ROSE = '#E8197A';
const INK  = '#14110D';
const MUTE = '#6B6B6B';

function header(doc: jsPDF, title: string, idLabel: string): void {
  // Brand bar across the top
  doc.setFillColor(CYAN);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 4, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(CYAN);
  doc.text('RESIHUB', 14, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(MUTE);
  doc.text('Student Accommodation Platform', 14, 18);

  // Title block (right)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(INK);
  const w = doc.internal.pageSize.getWidth();
  doc.text(title, w - 14, 16, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(MUTE);
  doc.text(idLabel, w - 14, 22, { align: 'right' });
}

function footer(doc: jsPDF): void {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setDrawColor(220);
  doc.line(14, h - 18, w - 14, h - 18);
  doc.setFontSize(8);
  doc.setTextColor(MUTE);
  doc.text('Generated by ResiHub · Built by Athera', 14, h - 12);
  doc.text(new Date().toLocaleDateString('en-ZA', { day: '2-digit', month: 'long', year: 'numeric' }),
           w - 14, h - 12, { align: 'right' });
  doc.text('This is a system-generated document. Contact your residence office for any disputes.',
           14, h - 8);
}

// ─────────────────────────────────────────────────────────────────
// Invoice PDF
// ─────────────────────────────────────────────────────────────────

export function downloadInvoicePdf(data: InvoiceData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  header(doc, 'INVOICE', `INV-${data.id.slice(-8).toUpperCase()}`);

  // Bill-to / Bill-from columns
  let y = 36;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(MUTE);
  doc.text('BILL TO', 14, y);
  doc.text('PERIOD', w / 2 + 5, y);

  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text(data.user.name, 14, y);
  doc.text(formatPeriod(data.period), w / 2 + 5, y);

  y += 5;
  doc.setFontSize(9);
  doc.setTextColor(MUTE);
  doc.text(data.user.email, 14, y);
  doc.text(`Issued ${new Date(data.createdAt).toLocaleDateString('en-ZA')}`, w / 2 + 5, y);

  if (data.user.phone) { y += 4; doc.text(data.user.phone, 14, y); }
  if (data.room) {
    y += 4;
    doc.text(`Room ${data.room.number} · Block ${data.room.block} · ${data.room.type}`, 14, y);
  }

  // Status pill
  y = 36;
  const statusLabel = data.proofStatus === 'CLEARED' ? 'PAID'
                    : data.proofStatus === 'SUBMITTED' ? 'UNDER REVIEW'
                    : data.proofStatus === 'REJECTED'  ? 'PROOF REJECTED'
                    : (data.status ?? 'PENDING').toUpperCase();
  const isPaid = statusLabel === 'PAID';
  doc.setFillColor(isPaid ? '#16a34a' : ROSE);
  doc.setTextColor('#FFFFFF');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  const padX = 6, padY = 2.5;
  const pillW = doc.getTextWidth(statusLabel) + padX * 2;
  doc.roundedRect(w - 14 - pillW, y - 5, pillW, 8, 2, 2, 'F');
  doc.text(statusLabel, w - 14 - pillW / 2, y - 0.2, { align: 'center', baseline: 'middle' });
  void padY; // silence

  // Line items table
  autoTable(doc, {
    startY: 70,
    head:   [['Description', 'Period', 'Amount']],
    body: [[
      data.room
        ? `Monthly Rent — Room ${data.room.number} (${data.room.type})`
        : 'Monthly Rent — Student Accommodation',
      formatPeriod(data.period),
      formatRand(data.rentLineItem),
    ]],
    headStyles: {
      fillColor: [22, 22, 27],
      textColor: '#FFFFFF',
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 10, textColor: INK },
    columnStyles: { 2: { halign: 'right', fontStyle: 'bold' } },
    theme: 'grid',
    margin: { left: 14, right: 14 },
  });

  // Totals block
  const tableEnd = ((doc as unknown) as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(MUTE);
  doc.text('Subtotal', w - 60, tableEnd);
  doc.setTextColor(INK);
  doc.text(formatRand(data.rentLineItem), w - 14, tableEnd, { align: 'right' });

  doc.setDrawColor(180);
  doc.line(w - 60, tableEnd + 2, w - 14, tableEnd + 2);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('TOTAL DUE', w - 60, tableEnd + 9);
  doc.setTextColor(CYAN);
  doc.text(formatRand(data.rentLineItem), w - 14, tableEnd + 9, { align: 'right' });

  // Payment instructions
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text('Payment instructions', 14, tableEnd + 24);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(MUTE);
  const lines = [
    '1. Pay via EFT to the residence bank account provided by your administrator.',
    `2. Use reference: INV-${data.id.slice(-8).toUpperCase()} so we can match your payment.`,
    '3. Upload your proof in the ResiHub app under Documents & Invoices.',
    '4. Admin will mark the invoice cleared once verified.',
  ];
  lines.forEach((line, i) => doc.text(line, 14, tableEnd + 31 + i * 5));

  footer(doc);
  doc.save(`Invoice-${formatPeriod(data.period).replace(/\s/g, '-')}-${data.user.name.split(' ')[0]}.pdf`);
}

// ─────────────────────────────────────────────────────────────────
// Contract PDF
// ─────────────────────────────────────────────────────────────────

export function downloadContractPdf(data: ContractData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  header(doc, 'LEASE AGREEMENT', `CTR-${data.id.slice(-8).toUpperCase()}`);

  let y = 40;
  // Parties
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text('Tenant', 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  y += 5; doc.text(data.user.name, 14, y);
  y += 5; doc.setTextColor(MUTE); doc.text(data.user.email, 14, y);

  // Room block on right
  let yR = 40;
  if (data.room) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(INK);
    doc.text('Premises', w / 2 + 5, yR);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    yR += 5; doc.text(`Room ${data.room.number} · Block ${data.room.block}`, w / 2 + 5, yR);
    yR += 5; doc.setTextColor(MUTE); doc.text(`${data.room.type} · ${formatRand(data.room.price)}/month`, w / 2 + 5, yR);
  }

  // Period band
  y += 12;
  doc.setFillColor(245, 248, 250);
  doc.rect(14, y, w - 28, 14, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(MUTE);
  doc.text('LEASE PERIOD', 18, y + 5);
  doc.text('COMMENCEMENT', w / 2, y + 5);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text(formatPeriod(data.period), 18, y + 11);
  doc.text(new Date(data.startDate).toLocaleDateString('en-ZA', { day: '2-digit', month: 'long', year: 'numeric' }),
           w / 2, y + 11);

  // Terms
  y += 22;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text('Terms and Conditions', 14, y);

  const terms = [
    '1. The tenant shall occupy the premises described above for the duration of the agreed lease period.',
    '2. Monthly rent is payable in advance, on or before the 1st of each calendar month, via the methods specified by the residence administrator.',
    '3. The tenant shall maintain the premises in a clean and orderly condition and shall be liable for any damage beyond normal wear-and-tear.',
    '4. Visitors are permitted in line with the residence visitor policy. The tenant is responsible for the conduct of their visitors.',
    '5. Either party may terminate this agreement on one calendar month\'s written notice, save for breaches that warrant immediate termination.',
    '6. The tenant agrees to abide by all residence house rules, including those relating to noise, security and shared facilities.',
    '7. This agreement is governed by the laws of the Republic of South Africa.',
  ];

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(MUTE);
  let ty = y + 6;
  for (const t of terms) {
    const wrapped = doc.splitTextToSize(t, w - 28);
    doc.text(wrapped, 14, ty);
    ty += wrapped.length * 4.5 + 2;
  }

  // Signature block
  ty += 8;
  doc.setDrawColor(180);
  doc.line(14, ty, w / 2 - 4, ty);
  doc.line(w / 2 + 4, ty, w - 14, ty);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(MUTE);
  doc.text('Tenant signature', 14, ty + 4);
  doc.text('Date', w / 2 + 4, ty + 4);

  if (data.signedAt && data.signedByName) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(11);
    doc.setTextColor(CYAN);
    doc.text(data.signedByName, 14, ty - 2);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(MUTE);
    doc.text(new Date(data.signedAt).toLocaleDateString('en-ZA', { day: '2-digit', month: 'long', year: 'numeric' }),
             w / 2 + 4, ty - 2);
    // E-signature stamp
    doc.setFontSize(7);
    doc.text(`Electronically signed via ResiHub · ${new Date(data.signedAt).toISOString()}`, 14, ty + 9);
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(ROSE);
    doc.text('Awaiting e-signature', 14, ty + 9);
  }

  footer(doc);
  doc.save(`Lease-${data.user.name.split(' ')[0]}.pdf`);
}

// ─────────────────────────────────────────────────────────────────
// Residence Health Report PDF — admin-only
// Multi-page: snapshot, financials, occupancy, ops, contractors,
// late payers, tickets summary. Designed to be printable + emailable.
// ─────────────────────────────────────────────────────────────────

export interface HealthReportData {
  residenceName: string;
  generatedAt:   Date;
  stats: {
    students:      { total: number; pending: number };
    rooms:         { total: number; occupied: number; vacant: number; totalSlots: number; filledSlots: number; slotOccupancyRate: number };
    maintenance:   { open: number; urgent: number };
    visitors:      { total: number; today: number };
    vouchers:      { active: number };
    monthlyRevenue:        number;
    monthlyOpsCost:        number;
    monthlyContractorCost: number;
    monthlyTotalCost:      number;
    netMonthly:            number;
    occupancyRate:         number;
  };
  ops: {
    monthlyOpsCost: number;
    spend30: Array<{ type: string; total: number; count: number }>;
    solarKwhLast30: number;
    stock: Array<{ label: string; quantity: number; unit: string; threshold: number | null; low: boolean }>;
    reminders: Array<{ severity: 'urgent' | 'warn' | 'info'; title: string; body: string }>;
    cadence: Array<{ type: string; lastDate: string | null; daysSinceLast: number | null; isOverdue: boolean }>;
  };
  revenue: {
    projectedMonthly: number;
    monthlyBreakdown: Array<{ period: string; expected: number; cleared: number; submitted: number; pending: number }>;
    latePayers: Array<{ user: { name: string; email: string }; period: string; amount: string | null; status: string | null }>;
    totalActiveStudents: number;
  };
  contractors: Array<{ name: string; type: string; rate: string; rateUnit: string; active: boolean; paymentType: string; pendingInvoiceCount: number; pendingInvoiceTotal: number }>;
}

const TYPE_LABELS: Record<string, string> = {
  POOL_CLEAN: 'Pool cleaning',  POOL_CHEMICAL: 'Pool chemicals',
  GAS_REFILL: 'Gas refill',     GRASS_CUT: 'Grass cut',
  ELECTRICITY_PURCHASE: 'Electricity', SOLAR_TELEMETRY: 'Solar reading',
  OTHER: 'Other',
  CLEANER: 'Cleaner', GROUNDSKEEPER: 'Grounds-keeper',
  GARDENER: 'Gardener',
};
const prettyType = (t: string) => TYPE_LABELS[t] ?? t.toLowerCase().replace(/_/g, ' ');

function ensureSpace(doc: jsPDF, y: number, lines = 20): number {
  const h = doc.internal.pageSize.getHeight();
  if (y + lines > h - 25) {
    doc.addPage();
    return 24;
  }
  return y;
}

function sectionHeader(doc: jsPDF, label: string, y: number): number {
  y = ensureSpace(doc, y, 14);
  doc.setFillColor(CYAN);
  doc.rect(14, y - 4, 2, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text(label, 19, y + 2);
  doc.setDrawColor(225);
  doc.line(14, y + 6, doc.internal.pageSize.getWidth() - 14, y + 6);
  return y + 12;
}

function kpiRow(doc: jsPDF, items: Array<{ label: string; value: string; tone?: 'good' | 'warn' | 'bad' | 'mute' }>, y: number): number {
  const w = doc.internal.pageSize.getWidth();
  const cellW = (w - 28) / items.length;
  items.forEach((it, i) => {
    const x = 14 + i * cellW;
    doc.setDrawColor(230);
    doc.roundedRect(x, y, cellW - 4, 18, 2, 2);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(MUTE);
    doc.text(it.label.toUpperCase(), x + 3, y + 5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    const tone = it.tone ?? 'mute';
    doc.setTextColor(
      tone === 'good' ? '#16a34a'
      : tone === 'bad'  ? ROSE
      : tone === 'warn' ? '#ea580c'
      : INK,
    );
    doc.text(it.value, x + 3, y + 13);
  });
  return y + 22;
}

export function downloadHealthReportPdf(data: HealthReportData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  header(doc, 'HEALTH REPORT', data.residenceName);

  let y = 32;

  // ── Generated note ───────────────────────────────────────────
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(MUTE);
  doc.text(
    `Generated ${data.generatedAt.toLocaleString('en-ZA', {
      day: '2-digit', month: 'long', year: 'numeric',
      hour: '2-digit', minute: '2-digit',
    })}`,
    14, y,
  );
  y += 10;

  // ── Financial snapshot ───────────────────────────────────────
  y = sectionHeader(doc, 'Financial snapshot · last 30 days', y);
  y = kpiRow(doc, [
    { label: 'Monthly revenue (expected)', value: formatRand(data.stats.monthlyRevenue),                tone: 'good' },
    { label: 'Total cost',                  value: formatRand(data.stats.monthlyTotalCost),              tone: 'warn' },
    { label: 'Net (rev − cost)',            value: formatRand(data.stats.netMonthly), tone: data.stats.netMonthly < 0 ? 'bad' : 'good' },
  ], y);
  y = kpiRow(doc, [
    { label: 'Ops cost',         value: formatRand(data.stats.monthlyOpsCost) },
    { label: 'Contractor cost',  value: formatRand(data.stats.monthlyContractorCost) },
    { label: 'Active students',  value: String(data.stats.students.total) },
  ], y);

  // ── Occupancy ────────────────────────────────────────────────
  y = sectionHeader(doc, 'Occupancy', y);
  y = kpiRow(doc, [
    { label: 'Bed-slot occupancy', value: `${data.stats.rooms.slotOccupancyRate}%`, tone: data.stats.rooms.slotOccupancyRate < 70 ? 'warn' : 'good' },
    { label: 'Filled / total slots', value: `${data.stats.rooms.filledSlots} / ${data.stats.rooms.totalSlots}` },
    { label: 'Pending applicants',  value: String(data.stats.students.pending), tone: data.stats.students.pending > 0 ? 'warn' : 'mute' },
  ], y);

  // ── Maintenance ──────────────────────────────────────────────
  y = sectionHeader(doc, 'Maintenance', y);
  y = kpiRow(doc, [
    { label: 'Open tickets',   value: String(data.stats.maintenance.open) },
    { label: 'Urgent / high',  value: String(data.stats.maintenance.urgent), tone: data.stats.maintenance.urgent > 0 ? 'bad' : 'good' },
    { label: "Today's visitors", value: String(data.stats.visitors.today) },
  ], y);

  // ── Ops spend by type ────────────────────────────────────────
  y = sectionHeader(doc, 'Operations spend · last 30 days', y);
  const opsRows = data.ops.spend30
    .filter(s => s.count > 0)
    .map(s => [prettyType(s.type), String(s.count), formatRand(s.total)]);
  if (opsRows.length === 0) opsRows.push(['No ops entries logged in the last 30 days', '', '']);
  autoTable(doc, {
    startY: y,
    head: [['Service', 'Entries', 'Spent']],
    body: opsRows,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 2 },
    headStyles: { fillColor: CYAN, textColor: '#FFFFFF', fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  // ── Stock alerts ─────────────────────────────────────────────
  if (data.ops.stock.length > 0) {
    y = sectionHeader(doc, 'Stock levels', y);
    autoTable(doc, {
      startY: y,
      head: [['Item', 'On hand', 'Threshold', 'Status']],
      body: data.ops.stock.map(s => [
        s.label,
        `${s.quantity} ${s.unit}`,
        s.threshold != null ? `${s.threshold} ${s.unit}` : '—',
        s.low ? 'LOW' : 'OK',
      ]),
      theme: 'grid',
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: CYAN, textColor: '#FFFFFF', fontStyle: 'bold' },
      didParseCell: (cell) => {
        if (cell.section === 'body' && cell.column.index === 3 && (cell.row.raw as unknown as string[])[3] === 'LOW') {
          cell.cell.styles.textColor = ROSE; cell.cell.styles.fontStyle = 'bold';
        }
      },
      margin: { left: 14, right: 14 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // ── Action items / reminders ─────────────────────────────────
  if (data.ops.reminders.length > 0) {
    y = sectionHeader(doc, 'Action items', y);
    data.ops.reminders.slice(0, 8).forEach(r => {
      y = ensureSpace(doc, y, 12);
      const dot = r.severity === 'urgent' ? ROSE : '#ea580c';
      doc.setFillColor(dot); doc.circle(16, y - 1, 1.2, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(INK);
      doc.text(r.title, 20, y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(MUTE);
      const lines = doc.splitTextToSize(r.body, w - 34);
      doc.text(lines, 20, y + 4);
      y += 4 + lines.length * 4 + 3;
    });
    y += 4;
  }

  // ── Late payers ──────────────────────────────────────────────
  y = sectionHeader(doc, 'Outstanding rent · late payers', y);
  const lateRows = data.revenue.latePayers.length === 0
    ? [['All caught up — no overdue rent', '', '', '']]
    : data.revenue.latePayers.slice(0, 12).map(lp => [
        lp.user.name,
        lp.user.email,
        lp.period,
        lp.amount ?? '—',
      ]);
  autoTable(doc, {
    startY: y,
    head: [['Tenant', 'Email', 'Period', 'Amount']],
    body: lateRows,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: ROSE, textColor: '#FFFFFF', fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  // ── Contractors ──────────────────────────────────────────────
  if (data.contractors.length > 0) {
    y = sectionHeader(doc, 'Contractors on file', y);
    autoTable(doc, {
      startY: y,
      head: [['Name', 'Role', 'Rate', 'Type', 'Status', 'Pending']],
      body: data.contractors.map(c => [
        c.name,
        prettyType(c.type),
        `${formatRand(c.rate)} / ${c.rateUnit}`,
        c.paymentType,
        c.active ? 'Active' : 'Ended',
        c.pendingInvoiceCount > 0 ? `${c.pendingInvoiceCount} (${formatRand(c.pendingInvoiceTotal)})` : '—',
      ]),
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: CYAN, textColor: '#FFFFFF', fontStyle: 'bold' },
      margin: { left: 14, right: 14 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // ── Telemetry note ──────────────────────────────────────────
  y = sectionHeader(doc, 'Live monitoring', y);
  y = ensureSpace(doc, y, 16);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(INK);
  doc.text(`Solar (manual entry only): ${data.ops.solarKwhLast30.toFixed(0)} kWh logged in last 30 days`, 14, y);
  y += 5;
  doc.setTextColor(MUTE);
  doc.setFontSize(8);
  doc.text('API integration pending for solar inverters and IP cameras. Once wired, live readings will replace manual logs.', 14, y);

  // ── Footer on every page ────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    footer(doc);
    doc.setFontSize(7);
    doc.setTextColor(MUTE);
    doc.text(`Page ${i} of ${pageCount}`, w / 2, doc.internal.pageSize.getHeight() - 12, { align: 'center' });
  }

  const safeName = data.residenceName.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  const stamp    = data.generatedAt.toISOString().slice(0, 10);
  doc.save(`HealthReport-${safeName}-${stamp}.pdf`);
}

